---
# playbook for install MLNX_OFED-4.5-1.0.1.0 on Ubuntu 16.04
#
# Author: Vitaliy Razinkov <vitaliyra@mellanox.com>
#
- hosts: all
  vars:
#    mofed_url: unused
    mofed_site_place: "MLNX_OFED-4.5-1.0.1.0"
    mofed_file_name: "MLNX_OFED_LINUX-4.5-1.0.1.0-ubuntu16.04-x86_64.iso"
  tasks:
    - shell: lspci | grep Mellanox | awk '{print $1}' | wc -l
      register: check_mlnx_adapter
    - block:
      - name: Download MOFED image
        warn: false
        shell: |
          cd /tmp
          wget http://content.mellanox.com/ofed/{{ mofed_site_place }}/{{ mofed_file_name }}
      - name: Install MOFED
        warn: false
        shell: |
          mkdir -p /mnt/iso
          mount -o loop /tmp/{{ mofed_file_name }} /mnt/iso
          /mnt/iso/mlnxofedinstall --all -q
        register: install_mofed
      - name: Reboot after MOFED install
        reboot:
        when: install_mofed.changed
      when: "{{ (check_mlnx_adapter.stdout|int) != 0 }}"
  tags:
    - mellanox_ofed
